version: '3.8'

services:
  docker-ansible:
    container_name: docker-ansible
    image: anhnmt/docker-ansible:latest
    volumes:
      - .:/app
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    command:
      - /bin/bash
      - -c
      - |
        ansible-galaxy collection install -r requirements.yml
        tail -f /dev/null