- hosts: prometheus
  become: yes
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_scrape_configs:
#      - job_name: "prometheus"
#        scrape_interval: 5s
#        metrics_path: "/metrics"
#        static_configs:
#          - targets: [ "{{ ansible_host }}:9090" ]

      - job_name: 'node_exporter'
        scrape_interval: 5s
        static_configs:
          - targets: "{{ groups['node_exporter'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', '\\1:9100') | list + [ansible_host + ':9090'] }}"