- hosts: all
  gather_facts: false

  tasks:
    - name: Create .ssh directory if it does not exist
      connection: local
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: '0755'

    - name: Check if known_hosts exists
      connection: local
      ansible.builtin.stat:
        path: "~/.ssh/known_hosts"
      register: known_hosts_file

    - name: Create known_hosts file if it does not exist
      connection: local
      ansible.builtin.copy:
        content: ""
        dest: "~/.ssh/known_hosts"
      when: not known_hosts_file.stat.exists

    - name: Remove existing entry from known_hosts file
      local_action: shell ssh-keygen -R {{ ansible_host }}
      ignore_errors: true

    - name: Add host key to known_hosts file
      local_action: shell ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts
      changed_when: false

    - name: Gather Facts
      ansible.builtin.setup:
